version: "3"

services:
  pingcrm:
    build: ./pingcrm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pingcrm:/code
    ports:
      - 8000:8000
    env_file:
      - ./pingcrm/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pingcrm
      - POSTGRES_PASSWORD=pingcrm
      - POSTGRES_DB=pingcrm

volumes:
  postgres_data:
